version: "3"

services:
  app:
    build:
      context: .
    image: liquidcarbon/flask2fa
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data:/data
    command: >
      sh -c "python app.py"
