version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data:/data
    command: >
      sh -c "python app.py"
    env_file:
      - .env.dev
    environment:
      - ABC=777
